/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SetListSongPosition {
    songId: string;
    position: bigint;
}
export interface SetList {
    id: string;
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
    songIds: Array<string>;
}
export interface Song {
    id: string;
    backgroundColor: string;
    tempo: bigint;
    title: string;
    lyrics: string;
    createdAt: bigint;
    textSize: bigint;
    isBold: boolean;
    colorRanges: Array<ColorRange>;
    updatedAt: bigint;
    linesPerScroll: bigint;
    artist: string;
    image?: ExternalBlob;
    scrollSpeed: bigint;
    textColor: string;
}
export interface SaveSongResponse {
    songId?: string;
    errorMessage?: string;
    success: boolean;
    replaceExistingPrompt: boolean;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface ColorRange {
    end: bigint;
    color: string;
    start: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface FileHandleReference {
    isSetList: boolean;
    path: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    createSetList(name: string, songIds: Array<string>): Promise<string>;
    deleteSetList(id: string): Promise<void>;
    deleteSong(id: string): Promise<void>;
    exportData(): Promise<{
        songs: Array<Song>;
        setLists: Array<SetList>;
    }>;
    getAllSongs(): Promise<Array<Song>>;
    getFileHandleReference(id: string): Promise<FileHandleReference | null>;
    getSetListSongCount(setListId: string): Promise<bigint>;
    getSetListSongInfo(setListId: string): Promise<{
        songPositions: Array<SetListSongPosition>;
        setList: SetList;
    }>;
    getSong(id: string): Promise<Song>;
    getSongsInSetList(setListId: string): Promise<Array<Song>>;
    importData(data: {
        songs: Array<Song>;
        setLists: Array<SetList>;
    }): Promise<void>;
    isTitleUnique(title: string): Promise<boolean>;
    moveSongInSetList(setListId: string, songId: string, newPosition: bigint): Promise<void>;
    saveFileHandleReference(id: string, path: string, isSetList: boolean): Promise<void>;
    saveSong(id: string | null, title: string, artist: string, lyrics: string, scrollSpeed: bigint, tempo: bigint, backgroundColor: string, textColor: string, textSize: bigint, isBold: boolean, linesPerScroll: bigint, colorRanges: Array<ColorRange>, replaceExisting: boolean, image: ExternalBlob | null): Promise<SaveSongResponse>;
    updateSetList(id: string, name: string, songIds: Array<string>): Promise<void>;
}
import type { ColorRange as _ColorRange, ExternalBlob as _ExternalBlob, FileHandleReference as _FileHandleReference, SaveSongResponse as _SaveSongResponse, SetList as _SetList, Song as _Song, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async createSetList(arg0: string, arg1: Array<string>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createSetList(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSetList(arg0, arg1);
            return result;
        }
    }
    async deleteSetList(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSetList(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSetList(arg0);
            return result;
        }
    }
    async deleteSong(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSong(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSong(arg0);
            return result;
        }
    }
    async exportData(): Promise<{
        songs: Array<Song>;
        setLists: Array<SetList>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.exportData();
                return from_candid_record_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportData();
            return from_candid_record_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSongs(): Promise<Array<Song>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSongs();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSongs();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFileHandleReference(arg0: string): Promise<FileHandleReference | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileHandleReference(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileHandleReference(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSetListSongCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSetListSongCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSetListSongCount(arg0);
            return result;
        }
    }
    async getSetListSongInfo(arg0: string): Promise<{
        songPositions: Array<SetListSongPosition>;
        setList: SetList;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getSetListSongInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSetListSongInfo(arg0);
            return result;
        }
    }
    async getSong(arg0: string): Promise<Song> {
        if (this.processError) {
            try {
                const result = await this.actor.getSong(arg0);
                return from_candid_Song_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSong(arg0);
            return from_candid_Song_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSongsInSetList(arg0: string): Promise<Array<Song>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSongsInSetList(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSongsInSetList(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async importData(arg0: {
        songs: Array<Song>;
        setLists: Array<SetList>;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importData(await to_candid_record_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importData(await to_candid_record_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async isTitleUnique(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isTitleUnique(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isTitleUnique(arg0);
            return result;
        }
    }
    async moveSongInSetList(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.moveSongInSetList(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moveSongInSetList(arg0, arg1, arg2);
            return result;
        }
    }
    async saveFileHandleReference(arg0: string, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFileHandleReference(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFileHandleReference(arg0, arg1, arg2);
            return result;
        }
    }
    async saveSong(arg0: string | null, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: string, arg7: string, arg8: bigint, arg9: boolean, arg10: bigint, arg11: Array<ColorRange>, arg12: boolean, arg13: ExternalBlob | null): Promise<SaveSongResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSong(to_candid_opt_n20(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, await to_candid_opt_n21(this._uploadFile, this._downloadFile, arg13));
                return from_candid_SaveSongResponse_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSong(to_candid_opt_n20(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, await to_candid_opt_n21(this._uploadFile, this._downloadFile, arg13));
            return from_candid_SaveSongResponse_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSetList(arg0: string, arg1: string, arg2: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSetList(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSetList(arg0, arg1, arg2);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_SaveSongResponse_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SaveSongResponse): SaveSongResponse {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_Song_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Song): Promise<Song> {
    return await from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileHandleReference]): FileHandleReference | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    backgroundColor: string;
    tempo: bigint;
    title: string;
    lyrics: string;
    createdAt: bigint;
    textSize: bigint;
    isBold: boolean;
    colorRanges: Array<_ColorRange>;
    updatedAt: bigint;
    linesPerScroll: bigint;
    artist: string;
    image: [] | [_ExternalBlob];
    scrollSpeed: bigint;
    textColor: string;
}): Promise<{
    id: string;
    backgroundColor: string;
    tempo: bigint;
    title: string;
    lyrics: string;
    createdAt: bigint;
    textSize: bigint;
    isBold: boolean;
    colorRanges: Array<ColorRange>;
    updatedAt: bigint;
    linesPerScroll: bigint;
    artist: string;
    image?: ExternalBlob;
    scrollSpeed: bigint;
    textColor: string;
}> {
    return {
        id: value.id,
        backgroundColor: value.backgroundColor,
        tempo: value.tempo,
        title: value.title,
        lyrics: value.lyrics,
        createdAt: value.createdAt,
        textSize: value.textSize,
        isBold: value.isBold,
        colorRanges: value.colorRanges,
        updatedAt: value.updatedAt,
        linesPerScroll: value.linesPerScroll,
        artist: value.artist,
        image: record_opt_to_undefined(await from_candid_opt_n12(_uploadFile, _downloadFile, value.image)),
        scrollSpeed: value.scrollSpeed,
        textColor: value.textColor
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    songId: [] | [string];
    errorMessage: [] | [string];
    success: boolean;
    replaceExistingPrompt: boolean;
}): {
    songId?: string;
    errorMessage?: string;
    success: boolean;
    replaceExistingPrompt: boolean;
} {
    return {
        songId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.songId)),
        errorMessage: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.errorMessage)),
        success: value.success,
        replaceExistingPrompt: value.replaceExistingPrompt
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    songs: Array<_Song>;
    setLists: Array<_SetList>;
}): Promise<{
    songs: Array<Song>;
    setLists: Array<SetList>;
}> {
    return {
        songs: await from_candid_vec_n9(_uploadFile, _downloadFile, value.songs),
        setLists: value.setLists
    };
}
async function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Song>): Promise<Array<Song>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Song_n10(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_Song_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Song): Promise<_Song> {
    return await to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    songs: Array<Song>;
    setLists: Array<SetList>;
}): Promise<{
    songs: Array<_Song>;
    setLists: Array<_SetList>;
}> {
    return {
        songs: await to_candid_vec_n16(_uploadFile, _downloadFile, value.songs),
        setLists: value.setLists
    };
}
async function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    backgroundColor: string;
    tempo: bigint;
    title: string;
    lyrics: string;
    createdAt: bigint;
    textSize: bigint;
    isBold: boolean;
    colorRanges: Array<ColorRange>;
    updatedAt: bigint;
    linesPerScroll: bigint;
    artist: string;
    image?: ExternalBlob;
    scrollSpeed: bigint;
    textColor: string;
}): Promise<{
    id: string;
    backgroundColor: string;
    tempo: bigint;
    title: string;
    lyrics: string;
    createdAt: bigint;
    textSize: bigint;
    isBold: boolean;
    colorRanges: Array<_ColorRange>;
    updatedAt: bigint;
    linesPerScroll: bigint;
    artist: string;
    image: [] | [_ExternalBlob];
    scrollSpeed: bigint;
    textColor: string;
}> {
    return {
        id: value.id,
        backgroundColor: value.backgroundColor,
        tempo: value.tempo,
        title: value.title,
        lyrics: value.lyrics,
        createdAt: value.createdAt,
        textSize: value.textSize,
        isBold: value.isBold,
        colorRanges: value.colorRanges,
        updatedAt: value.updatedAt,
        linesPerScroll: value.linesPerScroll,
        artist: value.artist,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.image)) : candid_none(),
        scrollSpeed: value.scrollSpeed,
        textColor: value.textColor
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Song>): Promise<Array<_Song>> {
    return await Promise.all(value.map(async (x)=>await to_candid_Song_n17(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
