/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ColorRange {
  'end' : bigint,
  'color' : string,
  'start' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface FileHandleReference { 'isSetList' : boolean, 'path' : string }
export interface SaveSongResponse {
  'songId' : [] | [string],
  'errorMessage' : [] | [string],
  'success' : boolean,
  'replaceExistingPrompt' : boolean,
}
export interface SetList {
  'id' : string,
  'name' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'songIds' : Array<string>,
}
export interface SetListSongPosition { 'songId' : string, 'position' : bigint }
export interface Song {
  'id' : string,
  'backgroundColor' : string,
  'tempo' : bigint,
  'title' : string,
  'lyrics' : string,
  'createdAt' : bigint,
  'textSize' : bigint,
  'isBold' : boolean,
  'colorRanges' : Array<ColorRange>,
  'updatedAt' : bigint,
  'linesPerScroll' : bigint,
  'artist' : string,
  'image' : [] | [ExternalBlob],
  'scrollSpeed' : bigint,
  'textColor' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'createSetList' : ActorMethod<[string, Array<string>], string>,
  'deleteSetList' : ActorMethod<[string], undefined>,
  'deleteSong' : ActorMethod<[string], undefined>,
  'exportData' : ActorMethod<
    [],
    { 'songs' : Array<Song>, 'setLists' : Array<SetList> }
  >,
  'getAllSongs' : ActorMethod<[], Array<Song>>,
  'getFileHandleReference' : ActorMethod<[string], [] | [FileHandleReference]>,
  'getSetListSongCount' : ActorMethod<[string], bigint>,
  'getSetListSongInfo' : ActorMethod<
    [string],
    { 'songPositions' : Array<SetListSongPosition>, 'setList' : SetList }
  >,
  'getSong' : ActorMethod<[string], Song>,
  'getSongsInSetList' : ActorMethod<[string], Array<Song>>,
  'importData' : ActorMethod<
    [{ 'songs' : Array<Song>, 'setLists' : Array<SetList> }],
    undefined
  >,
  'isTitleUnique' : ActorMethod<[string], boolean>,
  'moveSongInSetList' : ActorMethod<[string, string, bigint], undefined>,
  'saveFileHandleReference' : ActorMethod<[string, string, boolean], undefined>,
  'saveSong' : ActorMethod<
    [
      [] | [string],
      string,
      string,
      string,
      bigint,
      bigint,
      string,
      string,
      bigint,
      boolean,
      bigint,
      Array<ColorRange>,
      boolean,
      [] | [ExternalBlob],
    ],
    SaveSongResponse
  >,
  'updateSetList' : ActorMethod<[string, string, Array<string>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];