/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ColorRange = IDL.Record({
  'end' : IDL.Nat,
  'color' : IDL.Text,
  'start' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Song = IDL.Record({
  'id' : IDL.Text,
  'backgroundColor' : IDL.Text,
  'tempo' : IDL.Nat,
  'title' : IDL.Text,
  'lyrics' : IDL.Text,
  'createdAt' : IDL.Int,
  'textSize' : IDL.Nat,
  'isBold' : IDL.Bool,
  'colorRanges' : IDL.Vec(ColorRange),
  'updatedAt' : IDL.Int,
  'linesPerScroll' : IDL.Int,
  'artist' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'scrollSpeed' : IDL.Nat,
  'textColor' : IDL.Text,
});
export const SetList = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'songIds' : IDL.Vec(IDL.Text),
});
export const FileHandleReference = IDL.Record({
  'isSetList' : IDL.Bool,
  'path' : IDL.Text,
});
export const SetListSongPosition = IDL.Record({
  'songId' : IDL.Text,
  'position' : IDL.Nat,
});
export const SaveSongResponse = IDL.Record({
  'songId' : IDL.Opt(IDL.Text),
  'errorMessage' : IDL.Opt(IDL.Text),
  'success' : IDL.Bool,
  'replaceExistingPrompt' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'createSetList' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [IDL.Text], []),
  'deleteSetList' : IDL.Func([IDL.Text], [], []),
  'deleteSong' : IDL.Func([IDL.Text], [], []),
  'exportData' : IDL.Func(
      [],
      [IDL.Record({ 'songs' : IDL.Vec(Song), 'setLists' : IDL.Vec(SetList) })],
      ['query'],
    ),
  'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'getFileHandleReference' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(FileHandleReference)],
      ['query'],
    ),
  'getSetListSongCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getSetListSongInfo' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'songPositions' : IDL.Vec(SetListSongPosition),
          'setList' : SetList,
        }),
      ],
      ['query'],
    ),
  'getSong' : IDL.Func([IDL.Text], [Song], ['query']),
  'getSongsInSetList' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
  'importData' : IDL.Func(
      [IDL.Record({ 'songs' : IDL.Vec(Song), 'setLists' : IDL.Vec(SetList) })],
      [],
      [],
    ),
  'isTitleUnique' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'moveSongInSetList' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'saveFileHandleReference' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [], []),
  'saveSong' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Bool,
        IDL.Int,
        IDL.Vec(ColorRange),
        IDL.Bool,
        IDL.Opt(ExternalBlob),
      ],
      [SaveSongResponse],
      [],
    ),
  'updateSetList' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ColorRange = IDL.Record({
    'end' : IDL.Nat,
    'color' : IDL.Text,
    'start' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Song = IDL.Record({
    'id' : IDL.Text,
    'backgroundColor' : IDL.Text,
    'tempo' : IDL.Nat,
    'title' : IDL.Text,
    'lyrics' : IDL.Text,
    'createdAt' : IDL.Int,
    'textSize' : IDL.Nat,
    'isBold' : IDL.Bool,
    'colorRanges' : IDL.Vec(ColorRange),
    'updatedAt' : IDL.Int,
    'linesPerScroll' : IDL.Int,
    'artist' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'scrollSpeed' : IDL.Nat,
    'textColor' : IDL.Text,
  });
  const SetList = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'songIds' : IDL.Vec(IDL.Text),
  });
  const FileHandleReference = IDL.Record({
    'isSetList' : IDL.Bool,
    'path' : IDL.Text,
  });
  const SetListSongPosition = IDL.Record({
    'songId' : IDL.Text,
    'position' : IDL.Nat,
  });
  const SaveSongResponse = IDL.Record({
    'songId' : IDL.Opt(IDL.Text),
    'errorMessage' : IDL.Opt(IDL.Text),
    'success' : IDL.Bool,
    'replaceExistingPrompt' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'createSetList' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [IDL.Text], []),
    'deleteSetList' : IDL.Func([IDL.Text], [], []),
    'deleteSong' : IDL.Func([IDL.Text], [], []),
    'exportData' : IDL.Func(
        [],
        [
          IDL.Record({
            'songs' : IDL.Vec(Song),
            'setLists' : IDL.Vec(SetList),
          }),
        ],
        ['query'],
      ),
    'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'getFileHandleReference' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(FileHandleReference)],
        ['query'],
      ),
    'getSetListSongCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getSetListSongInfo' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'songPositions' : IDL.Vec(SetListSongPosition),
            'setList' : SetList,
          }),
        ],
        ['query'],
      ),
    'getSong' : IDL.Func([IDL.Text], [Song], ['query']),
    'getSongsInSetList' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
    'importData' : IDL.Func(
        [
          IDL.Record({
            'songs' : IDL.Vec(Song),
            'setLists' : IDL.Vec(SetList),
          }),
        ],
        [],
        [],
      ),
    'isTitleUnique' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'moveSongInSetList' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'saveFileHandleReference' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'saveSong' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Bool,
          IDL.Int,
          IDL.Vec(ColorRange),
          IDL.Bool,
          IDL.Opt(ExternalBlob),
        ],
        [SaveSongResponse],
        [],
      ),
    'updateSetList' : IDL.Func([IDL.Text, IDL.Text, IDL.Vec(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };